console.log("Hello World!");
console.log("I am Sanu.");
let a=8;
let b=10;
console.log("Sum is:",a+b);
let pencilPrice=7;
let penPrice=10;
console.log(`The price of pencil is ${pencilPrice}`);
console.log(`The price of pen is ${penPrice}`);
let output=`The total price is:${pencilPrice+penPrice} rupees.`;
console.log(output);
